/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,js,ts}"],
  theme: {
    extend: {
      fontFamily: {
        title: [
          "Lack",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        content: [
          "Montserrat",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      colors: {
        primary: {
          DEFAULT: "#388A84",
          50: "#A1D9D5",
          100: "#92D3CE",
          200: "#75C7C1",
          300: "#58BBB4",
          400: "#44A7A0",
          500: "#388A84",
          600: "#28625E",
          700: "#183A38",
          800: "#071211",
          900: "#000000",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
};
